from __future__ import annotations

from typing import Protocol

from ..models import (
    ActionResult,
    AddAttachmentRequest,
    AttachmentResult,
    BulkCategorizeEmailsRequest,
    BulkDeleteEventsRequest,
    BulkMarkEmailsRequest,
    BulkRespondToInvitesRequest,
    DeleteAttachmentRequest,
    BulkDeleteEmailsRequest,
    BulkMoveEmailsRequest,
    BulkResult,
    AvailabilityResult,
    CalendarInfo,
    CalendarEvent,
    ContactFull,
    ContactSummary,
    CategorizeEmailRequest,
    CategoryUsage,
    CreateEventRequest,
    CreateEventResult,
    CreateContactRequest,
    CreateFolderRequest,
    DeleteContactRequest,
    DeleteEmailRequest,
    DeleteEventRequest,
    DeleteFolderRequest,
    DraftEmailRequest,
    EmailFull,
    EmailMimeResult,
    EmailSummary,
    FolderActionRequest,
    FolderInfo,
    FindFreeSlotsRequest,
    ForwardEmailRequest,
    FreeSlot,
    GetAttachmentRequest,
    GetContactRequest,
    GetEmailMimeRequest,
    GetEmailRequest,
    GetEventRequest,
    GetThreadRequest,
    ListCategoriesRequest,
    ListEmailsRequest,
    ListEventsRequest,
    ListFoldersRequest,
    ListRoomsRequest,
    MailboxInfo,
    DelegateInfo,
    CreateInboxRuleRequest,
    DeleteInboxRuleRequest,
    InboxRule,
    UpdateInboxRuleRequest,
    MarkEmailRequest,
    OutOfOfficeSettings,
    PingResult,
    RenameFolderRequest,
    ReplyEmailRequest,
    RespondToInviteRequest,
    RoomInfo,
    RoomListInfo,
    SearchContactsRequest,
    SearchEmailsRequest,
    SendDraftRequest,
    SendEmailRequest,
    SendResult,
    Thread,
    UpdateContactRequest,
    UpdateDraftRequest,
    UpdateEventRequest,
)


class ExchangeBackend(Protocol):
    def ping(self) -> PingResult: ...
    def get_mailbox_info(self) -> MailboxInfo: ...
    def get_out_of_office(self) -> OutOfOfficeSettings: ...
    def list_delegates(self) -> list[DelegateInfo]: ...
    def list_inbox_rules(self) -> list[InboxRule]: ...
    def create_inbox_rule(self, request: CreateInboxRuleRequest) -> InboxRule: ...
    def update_inbox_rule(self, request: UpdateInboxRuleRequest) -> InboxRule: ...
    def delete_inbox_rule(self, request: DeleteInboxRuleRequest) -> ActionResult: ...
    def set_out_of_office(self, request: OutOfOfficeSettings) -> OutOfOfficeSettings: ...
    def list_emails(self, request: ListEmailsRequest) -> list[EmailSummary]: ...
    def get_email(self, request: GetEmailRequest) -> EmailFull: ...
    def get_thread(self, request: GetThreadRequest) -> Thread: ...
    def search_emails(self, request: SearchEmailsRequest) -> list[EmailSummary]: ...
    def send_email(self, request: SendEmailRequest) -> SendResult: ...
    def reply_email(self, request: ReplyEmailRequest) -> SendResult: ...
    def forward_email(self, request: ForwardEmailRequest) -> SendResult: ...
    def move_email(self, request: FolderActionRequest) -> ActionResult: ...
    def copy_email(self, request: FolderActionRequest) -> ActionResult: ...
    def delete_email(self, request: DeleteEmailRequest) -> ActionResult: ...
    def mark_email(self, request: MarkEmailRequest) -> ActionResult: ...
    def move_emails(self, request: BulkMoveEmailsRequest) -> BulkResult: ...
    def copy_emails(self, request: BulkMoveEmailsRequest) -> BulkResult: ...
    def delete_emails(self, request: BulkDeleteEmailsRequest) -> BulkResult: ...
    def mark_emails(self, request: BulkMarkEmailsRequest) -> BulkResult: ...
    def categorize_emails(self, request: BulkCategorizeEmailsRequest) -> BulkResult: ...
    def categorize_email(self, request: CategorizeEmailRequest) -> ActionResult: ...
    def list_categories(self, request: ListCategoriesRequest) -> list[CategoryUsage]: ...
    def list_folders(self, request: ListFoldersRequest) -> list[FolderInfo]: ...
    def create_folder(self, request: CreateFolderRequest) -> ActionResult: ...
    def rename_folder(self, request: RenameFolderRequest) -> ActionResult: ...
    def delete_folder(self, request: DeleteFolderRequest) -> ActionResult: ...
    def create_draft(self, request: DraftEmailRequest) -> ActionResult: ...
    def update_draft(self, request: UpdateDraftRequest) -> ActionResult: ...
    def send_draft(self, request: SendDraftRequest) -> SendResult: ...
    def add_attachment(self, request: AddAttachmentRequest) -> ActionResult: ...
    def delete_attachment(self, request: DeleteAttachmentRequest) -> ActionResult: ...
    def get_attachment(self, request: GetAttachmentRequest) -> AttachmentResult: ...
    def get_email_mime(self, request: GetEmailMimeRequest) -> EmailMimeResult: ...
    def list_events(self, request: ListEventsRequest) -> list[CalendarEvent]: ...
    def get_event(self, request: GetEventRequest) -> CalendarEvent: ...
    def create_event(self, request: CreateEventRequest) -> CreateEventResult: ...
    def update_event(self, request: UpdateEventRequest) -> ActionResult: ...
    def delete_event(self, request: DeleteEventRequest) -> ActionResult: ...
    def respond_to_invite(self, request: RespondToInviteRequest) -> ActionResult: ...
    def find_free_slots(self, request: FindFreeSlotsRequest) -> list[FreeSlot]: ...
    def delete_events(self, request: BulkDeleteEventsRequest) -> BulkResult: ...
    def respond_to_invites(self, request: BulkRespondToInvitesRequest) -> BulkResult: ...
    def get_my_availability(self, request: ListEventsRequest) -> AvailabilityResult: ...
    def list_calendars(self) -> list[CalendarInfo]: ...
    def list_room_lists(self) -> list[RoomListInfo]: ...
    def list_rooms(self, request: ListRoomsRequest) -> list[RoomInfo]: ...
    def search_contacts(self, request: SearchContactsRequest) -> list[ContactSummary]: ...
    def get_contact(self, request: GetContactRequest) -> ContactFull: ...
    def create_contact(self, request: CreateContactRequest) -> ActionResult: ...
    def update_contact(self, request: UpdateContactRequest) -> ActionResult: ...
    def delete_contact(self, request: DeleteContactRequest) -> ActionResult: ...
