from __future__ import annotations

from typing import Protocol

from ..models import (
    ActionResult,
    AttachmentResult,
    AvailabilityResult,
    BulkCategorizeEmailsRequest,
    BulkDeleteEmailsRequest,
    BulkMarkEmailsRequest,
    BulkMoveEmailsRequest,
    CalendarInfo,
    CalendarEvent,
    ContactFull,
    ContactSummary,
    CategorizeEmailRequest,
    CategoryUsage,
    CreateEventRequest,
    CreateEventResult,
    CreateContactRequest,
    CreateFolderRequest,
    CreateRuleRequest,
    DeleteContactRequest,
    DeleteEmailRequest,
    DeleteEventRequest,
    DeleteFolderRequest,
    DeleteRuleRequest,
    DraftEmailRequest,
    EmailFull,
    EmailMimeResult,
    EmailSummary,
    FolderActionRequest,
    FolderInfo,
    FindFreeSlotsRequest,
    ForwardEmailRequest,
    FreeSlot,
    GetAttachmentRequest,
    GetContactRequest,
    GetEmailMimeRequest,
    GetEmailRequest,
    GetEventRequest,
    GetThreadRequest,
    ListCategoriesRequest,
    ListEmailsRequest,
    ListEventsRequest,
    ListFoldersRequest,
    ListRoomsRequest,
    MailboxInfo,
    MailRule,
    MarkEmailRequest,
    OofSettingsModel,
    PingResult,
    RenameFolderRequest,
    ReplyEmailRequest,
    RespondToInviteRequest,
    RoomInfo,
    RoomListInfo,
    SearchContactsRequest,
    SearchEmailsRequest,
    SendDraftRequest,
    SendEmailRequest,
    SendResult,
    SetOofSettingsRequest,
    Thread,
    UpdateContactRequest,
    UpdateDraftRequest,
    UpdateEventRequest,
    UpdateRuleRequest,
)


class ExchangeBackend(Protocol):
    def ping(self) -> PingResult: ...
    def get_mailbox_info(self) -> MailboxInfo: ...
    def list_emails(self, request: ListEmailsRequest) -> list[EmailSummary]: ...
    def get_email(self, request: GetEmailRequest) -> EmailFull: ...
    def get_thread(self, request: GetThreadRequest) -> Thread: ...
    def search_emails(self, request: SearchEmailsRequest) -> list[EmailSummary]: ...
    def send_email(self, request: SendEmailRequest) -> SendResult: ...
    def reply_email(self, request: ReplyEmailRequest) -> SendResult: ...
    def forward_email(self, request: ForwardEmailRequest) -> SendResult: ...
    def move_email(self, request: FolderActionRequest) -> ActionResult: ...
    def copy_email(self, request: FolderActionRequest) -> ActionResult: ...
    def delete_email(self, request: DeleteEmailRequest) -> ActionResult: ...
    def mark_email(self, request: MarkEmailRequest) -> ActionResult: ...
    def categorize_email(self, request: CategorizeEmailRequest) -> ActionResult: ...
    def bulk_move_emails(self, request: BulkMoveEmailsRequest) -> list[ActionResult]: ...
    def bulk_delete_emails(self, request: BulkDeleteEmailsRequest) -> list[ActionResult]: ...
    def bulk_mark_emails(self, request: BulkMarkEmailsRequest) -> list[ActionResult]: ...
    def bulk_categorize_emails(
        self, request: BulkCategorizeEmailsRequest
    ) -> list[ActionResult]: ...
    def list_categories(self, request: ListCategoriesRequest) -> list[CategoryUsage]: ...
    def list_folders(self, request: ListFoldersRequest) -> list[FolderInfo]: ...
    def create_folder(self, request: CreateFolderRequest) -> ActionResult: ...
    def rename_folder(self, request: RenameFolderRequest) -> ActionResult: ...
    def delete_folder(self, request: DeleteFolderRequest) -> ActionResult: ...
    def create_draft(self, request: DraftEmailRequest) -> ActionResult: ...
    def update_draft(self, request: UpdateDraftRequest) -> ActionResult: ...
    def send_draft(self, request: SendDraftRequest) -> SendResult: ...
    def get_attachment(self, request: GetAttachmentRequest) -> AttachmentResult: ...
    def get_email_mime(self, request: GetEmailMimeRequest) -> EmailMimeResult: ...
    def list_rules(self) -> list[MailRule]: ...
    def create_rule(self, request: CreateRuleRequest) -> ActionResult: ...
    def update_rule(self, request: UpdateRuleRequest) -> ActionResult: ...
    def delete_rule(self, request: DeleteRuleRequest) -> ActionResult: ...
    def get_oof_settings(self) -> OofSettingsModel: ...
    def set_oof_settings(self, request: SetOofSettingsRequest) -> ActionResult: ...
    def list_events(self, request: ListEventsRequest) -> list[CalendarEvent]: ...
    def get_event(self, request: GetEventRequest) -> CalendarEvent: ...
    def create_event(self, request: CreateEventRequest) -> CreateEventResult: ...
    def update_event(self, request: UpdateEventRequest) -> ActionResult: ...
    def delete_event(self, request: DeleteEventRequest) -> ActionResult: ...
    def respond_to_invite(self, request: RespondToInviteRequest) -> ActionResult: ...
    def find_free_slots(self, request: FindFreeSlotsRequest) -> list[FreeSlot]: ...
    def get_my_availability(self, request: ListEventsRequest) -> AvailabilityResult: ...
    def list_calendars(self) -> list[CalendarInfo]: ...
    def list_room_lists(self) -> list[RoomListInfo]: ...
    def list_rooms(self, request: ListRoomsRequest) -> list[RoomInfo]: ...
    def search_contacts(self, request: SearchContactsRequest) -> list[ContactSummary]: ...
    def get_contact(self, request: GetContactRequest) -> ContactFull: ...
    def create_contact(self, request: CreateContactRequest) -> ActionResult: ...
    def update_contact(self, request: UpdateContactRequest) -> ActionResult: ...
    def delete_contact(self, request: DeleteContactRequest) -> ActionResult: ...
