from __future__ import annotations

from . import models
from .mcp_tools import ToolSpec
from .tools.calendar import (
    create_event,
    delete_event,
    find_free_slots,
    get_event,
    get_my_availability,
    list_calendars,
    list_events,
    respond_to_invite,
    update_event,
)
from .tools.contacts import (
    create_contact,
    delete_contact,
    get_contact,
    search_contacts,
    update_contact,
)
from .tools.email import (
    categorize_email,
    copy_email,
    create_draft,
    create_folder,
    delete_email,
    forward_email,
    get_attachment,
    get_email,
    list_categories,
    list_emails,
    list_folders,
    mark_email,
    move_email,
    reply_email,
    search_emails,
    send_draft,
    send_email,
)
from .tools.system import get_mailbox_info, ping_exchange

#: The single source of truth for every Outlook MCP tool: name, description,
#: handler, request/response schema, and MCP annotations all live together so
#: adding a tool means adding one entry here instead of touching N call sites.
TOOL_SPECS: list[ToolSpec] = [
    ToolSpec(
        "ping_exchange",
        "Check connectivity to Exchange",
        ping_exchange,
        response_model=models.PingResult,
        read_only=True,
    ),
    ToolSpec(
        "get_mailbox_info",
        "Get mailbox metadata",
        get_mailbox_info,
        response_model=models.MailboxInfo,
        read_only=True,
    ),
    ToolSpec(
        "list_emails",
        "List emails in a folder",
        list_emails,
        request_model=models.ListEmailsRequest,
        response_model=list[models.EmailSummary],
        read_only=True,
    ),
    ToolSpec(
        "get_email",
        "Get a full email by ID",
        get_email,
        request_model=models.GetEmailRequest,
        response_model=models.EmailFull,
        read_only=True,
    ),
    ToolSpec(
        "search_emails",
        "Search emails",
        search_emails,
        request_model=models.SearchEmailsRequest,
        response_model=list[models.EmailSummary],
        read_only=True,
    ),
    ToolSpec(
        "send_email",
        "Send a new email",
        send_email,
        request_model=models.SendEmailRequest,
        response_model=models.SendResult,
        destructive=True,
    ),
    ToolSpec(
        "reply_email",
        "Reply to an email",
        reply_email,
        request_model=models.ReplyEmailRequest,
        response_model=models.SendResult,
        destructive=True,
    ),
    ToolSpec(
        "forward_email",
        "Forward an email",
        forward_email,
        request_model=models.ForwardEmailRequest,
        response_model=models.SendResult,
        destructive=True,
    ),
    ToolSpec(
        "move_email",
        "Move email to another folder",
        move_email,
        request_model=models.FolderActionRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
    ToolSpec(
        "copy_email",
        "Copy email to another folder",
        copy_email,
        request_model=models.FolderActionRequest,
        response_model=models.ActionResult,
    ),
    ToolSpec(
        "delete_email",
        "Delete an email",
        delete_email,
        request_model=models.DeleteEmailRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
    ToolSpec(
        "mark_email",
        "Update read state, importance, or the follow-up flag "
        "(optionally with start and due dates)",
        mark_email,
        request_model=models.MarkEmailRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
    ToolSpec(
        "categorize_email",
        "Set, add, or remove Outlook categories (the coloured labels) on an email",
        categorize_email,
        request_model=models.CategorizeEmailRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
    ToolSpec(
        "list_categories",
        "List the categories in use, with counts. Collected from the most recent "
        "messages of the given folders, not from the mailbox master category list.",
        list_categories,
        request_model=models.ListCategoriesRequest,
        response_model=list[models.CategoryUsage],
        read_only=True,
    ),
    ToolSpec(
        "list_folders",
        "List mailbox folders",
        list_folders,
        request_model=models.ListFoldersRequest,
        response_model=list[models.FolderInfo],
        read_only=True,
    ),
    ToolSpec(
        "create_folder",
        "Create a mailbox folder",
        create_folder,
        request_model=models.CreateFolderRequest,
        response_model=models.ActionResult,
    ),
    ToolSpec(
        "create_draft",
        "Create an email draft",
        create_draft,
        request_model=models.DraftEmailRequest,
        response_model=models.ActionResult,
    ),
    ToolSpec(
        "send_draft",
        "Send a draft email",
        send_draft,
        request_model=models.SendDraftRequest,
        response_model=models.SendResult,
        destructive=True,
    ),
    ToolSpec(
        "get_attachment",
        "Save an attachment to disk",
        get_attachment,
        request_model=models.GetAttachmentRequest,
        response_model=models.AttachmentResult,
    ),
    ToolSpec(
        "list_events",
        "List calendar events in a time range",
        list_events,
        request_model=models.ListEventsRequest,
        response_model=list[models.CalendarEvent],
        read_only=True,
    ),
    ToolSpec(
        "get_event",
        "Get a calendar event by ID",
        get_event,
        request_model=models.GetEventRequest,
        response_model=models.CalendarEvent,
        read_only=True,
    ),
    ToolSpec(
        "create_event",
        "Create a calendar event",
        create_event,
        request_model=models.CreateEventRequest,
        response_model=models.CreateEventResult,
        destructive=True,
    ),
    ToolSpec(
        "update_event",
        "Update a calendar event",
        update_event,
        request_model=models.UpdateEventRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
    ToolSpec(
        "delete_event",
        "Delete a calendar event",
        delete_event,
        request_model=models.DeleteEventRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
    ToolSpec(
        "respond_to_invite",
        "Respond to a calendar invite",
        respond_to_invite,
        request_model=models.RespondToInviteRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
    ToolSpec(
        "find_free_slots",
        "Find meeting time slots",
        find_free_slots,
        request_model=models.FindFreeSlotsRequest,
        response_model=list[models.FreeSlot],
        read_only=True,
    ),
    ToolSpec(
        "get_my_availability",
        "Get free and busy slots",
        get_my_availability,
        request_model=models.ListEventsRequest,
        response_model=models.AvailabilityResult,
        read_only=True,
    ),
    ToolSpec(
        "list_calendars",
        "List calendars",
        list_calendars,
        response_model=list[models.CalendarInfo],
        read_only=True,
    ),
    ToolSpec(
        "search_contacts",
        "Search contacts",
        search_contacts,
        request_model=models.SearchContactsRequest,
        response_model=list[models.ContactSummary],
        read_only=True,
    ),
    ToolSpec(
        "get_contact",
        "Get a contact by ID",
        get_contact,
        request_model=models.GetContactRequest,
        response_model=models.ContactFull,
        read_only=True,
    ),
    ToolSpec(
        "create_contact",
        "Create a personal contact",
        create_contact,
        request_model=models.CreateContactRequest,
        response_model=models.ActionResult,
    ),
    ToolSpec(
        "update_contact",
        "Update a personal contact",
        update_contact,
        request_model=models.UpdateContactRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
    ToolSpec(
        "delete_contact",
        "Delete a personal contact",
        delete_contact,
        request_model=models.DeleteContactRequest,
        response_model=models.ActionResult,
        destructive=True,
    ),
]
